import "server-only";
import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { cryptoEnv } from "@/lib/env";

const ALGORITHM = "aes-256-gcm" as const;
const IV_LENGTH = 12; // bytes, GCM standard nonce size
const AUTH_TAG_LENGTH = 16; // bytes

/** Everything a connector's OAuth exchange returns, as one opaque bundle. */
export type ProviderTokenBundle = Record<string, unknown>;

export interface SealedSecret {
  /** ciphertext with the GCM auth tag appended */
  ciphertext: Buffer;
  iv: Buffer;
  keyVersion: number;
  alg: typeof ALGORITHM;
}

let keyring: Map<number, Buffer> | undefined;
let activeVersion: number | undefined;

/**
 * TOKEN_ENC_KEYS format: "1:<base64 32B>,2:<base64 32B>". Keeping every
 * historical version loadable (not just the active one) is what makes key
 * rotation a background re-seal job instead of a "decrypt everything or
 * lose it" outage.
 */
function loadKeyring(): { keyring: Map<number, Buffer>; activeVersion: number } {
  if (keyring && activeVersion !== undefined) {
    return { keyring, activeVersion };
  }
  const env = cryptoEnv();
  const map = new Map<number, Buffer>();
  for (const entry of env.TOKEN_ENC_KEYS.split(",")) {
    const [versionStr, b64] = entry.split(":");
    if (!versionStr || !b64) {
      throw new Error(`TOKEN_ENC_KEYS: malformed entry "${entry}"`);
    }
    const version = Number(versionStr);
    const key = Buffer.from(b64, "base64");
    if (key.length !== 32) {
      throw new Error(`TOKEN_ENC_KEYS: key version ${version} must decode to 32 bytes, got ${key.length}`);
    }
    map.set(version, key);
  }
  const active = Number(env.TOKEN_ENC_ACTIVE_VERSION);
  if (!map.has(active)) {
    throw new Error(`TOKEN_ENC_ACTIVE_VERSION (${active}) has no matching entry in TOKEN_ENC_KEYS`);
  }
  keyring = map;
  activeVersion = active;
  return { keyring: map, activeVersion: active };
}

function keyFor(version: number): Buffer {
  const { keyring: ring } = loadKeyring();
  const key = ring.get(version);
  if (!key) {
    throw new Error(`No encryption key registered for version ${version}`);
  }
  return key;
}

/**
 * Additional authenticated data binds the ciphertext to the specific row it
 * belongs to. Without this, a ciphertext copied from one credential row into
 * another (e.g. via a buggy migration or a copy-paste in an admin tool)
 * would decrypt "successfully" under the wrong workspace/credential. With
 * it, GCM's tag verification fails and openTokens() throws.
 */
function aad(workspaceId: string, credentialId: string): Buffer {
  return Buffer.from(`v1|${workspaceId}|${credentialId}`, "utf8");
}

/**
 * Encrypt a provider's full token bundle as one JSON blob. Never store one
 * column per token field — providers disagree on what they return, and a
 * single AEAD blob means adding a field (id_token, workspace metadata, ...)
 * is not a migration.
 *
 * `credentialId` must be generated by the caller BEFORE insert (e.g.
 * `crypto.randomUUID()`), not left to a DB column default, because it is
 * bound into the ciphertext here.
 */
export function sealTokens(
  plaintext: ProviderTokenBundle,
  workspaceId: string,
  credentialId: string,
): SealedSecret {
  const { activeVersion: version } = loadKeyring();
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, keyFor(version), iv);
  cipher.setAAD(aad(workspaceId, credentialId));

  const encrypted = Buffer.concat([
    cipher.update(JSON.stringify(plaintext), "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();

  return {
    ciphertext: Buffer.concat([encrypted, authTag]),
    iv,
    keyVersion: version,
    alg: ALGORITHM,
  };
}

/**
 * Decrypt a sealed secret. Throws if the AAD (workspace/credential id) does
 * not match the ciphertext it was sealed under, or if the ciphertext has
 * been tampered with — do not catch this broadly and fall back to "treat as
 * invalid credential"; a thrown auth-tag mismatch is a security event, not
 * routine control flow.
 */
export function openTokens(
  sealed: SealedSecret,
  workspaceId: string,
  credentialId: string,
): ProviderTokenBundle {
  const authTag = sealed.ciphertext.subarray(sealed.ciphertext.length - AUTH_TAG_LENGTH);
  const body = sealed.ciphertext.subarray(0, sealed.ciphertext.length - AUTH_TAG_LENGTH);

  const decipher = createDecipheriv(ALGORITHM, keyFor(sealed.keyVersion), sealed.iv);
  decipher.setAAD(aad(workspaceId, credentialId));
  decipher.setAuthTag(authTag);

  const decrypted = Buffer.concat([decipher.update(body), decipher.final()]);
  return JSON.parse(decrypted.toString("utf8")) as ProviderTokenBundle;
}

/** Whether a sealed secret was encrypted under an old key version. */
export function needsRotation(sealed: Pick<SealedSecret, "keyVersion">): boolean {
  const { activeVersion: version } = loadKeyring();
  return sealed.keyVersion !== version;
}

/**
 * PostgREST/Postgres exchange `bytea` columns as a `\x`-prefixed hex string
 * over the JSON API, never as a raw byte array — handing a Buffer straight
 * to supabase-js would get JSON.stringify'd into `{"type":"Buffer","data":
 * [...]}`, which Postgres cannot cast to bytea at all. Use these at every
 * boundary where a Buffer crosses into or out of a bytea column.
 */
export function toBytea(buffer: Buffer): string {
  return `\\x${buffer.toString("hex")}`;
}

export function fromBytea(value: string): Buffer {
  return Buffer.from(value.replace(/^\\x/, ""), "hex");
}
