import type { SkillRef } from '@intellidev/shared'

/**
 * The project's context document, rendered per harness.
 *
 * One source (`context/repo.md` in the bundle) becomes `CLAUDE.md`, `AGENTS.md` or an
 * `instructions` entry. The text is identical; what differs is whether a skill index has
 * to be appended.
 */

export const GENERATED_HEADER =
  '<!-- Generated by intellidev from the project manifest. Edit the manifest, not this file. -->'

/**
 * Append a skill index only for harnesses with no native skill loading.
 *
 * Claude Code and opencode discover skills from a directory and load them on demand,
 * which gives progressive disclosure — the model reads a one-line summary and pulls the
 * body only when relevant. Pasting the index into their context file would waste tokens
 * duplicating what they already do better.
 *
 * Codex has no skill primitive, so for it the index is the only way a skill is
 * discoverable at all, and the gateway's `skill_load` is how the body arrives.
 */
export function renderContextDocument(args: {
  context: string
  skills: readonly SkillRef[]
  includeSkillIndex: boolean
}): string {
  const parts = [GENERATED_HEADER, '', args.context.trim()]

  if (args.includeSkillIndex && args.skills.length > 0) {
    parts.push(
      '',
      '## Available skills',
      '',
      'This harness has no native skill loading, so use the `skill_load` tool to read one.',
      '',
      ...[...args.skills]
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((skill) => `- **${skill.name}** — ${skill.description ?? 'no summary provided'}`),
    )
  }

  return `${parts.join('\n').trimEnd()}\n`
}
